substitutions:
  name: vacuum-door-controller-817097

packages:
  alexanderwassbjer.vacuum-door-controller: github://alexanderwassbjer/vacuum-door-controller/vacuum-door-controller/esp8266.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m
  # restore_from_flash: true

api:
  encryption:
    key: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
