---
# Vacuum Door Controller
#
# Controls a linear actuator to open and close a door.
# Is used in my case for a vacuum door.
# © Alexander Wassbjer
#
substitutions:
  device_name: vacuum-door-controller
  friendly_name: Vacuum Door Controller
  project_version: "1.0.1"
  device_description: "Controls a linear actuator to open and close a door - ESP8266 Generic"

  # Define the GPIO pins
  motor_in1_pin: GPIO5
  motor_in2_pin: GPIO4
  motor_enabled_pin: GPIO14

esphome:
  name: "${device_name}"
  comment: "${device_description}"
  name_add_mac_suffix: false
  project:
    name: "alexanderwassbjer.vacuum-door-controller"
    version: "${project_version}"

esp8266:
  board: esp01_1m

packages:
  remote_package:
    url: https://github.com/alexanderwassbjer/vacuum-door-controller/
    ref: main
    files:
      - components/basis.yaml

# Enable logging
logger:

# Enable OTA updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ap:
    ssid: "${friendly_name}"

# Enable captive portal for setting WiFi credentials
captive_portal:

web_server:
