# Door controls config #

# Define script to control the door
script:
  - id: open_door
    then:
      - globals.set:
          id: door_state_open
          value: "true"
      - switch.turn_off: motor_in1
      - switch.turn_on: motor_in2
      - delay: !lambda "return id(open_delay).state * 1000;"
      - script.execute: stop_door

  - id: close_door
    then:
      - globals.set:
          id: door_state_open
          value: "false"
      - switch.turn_on: motor_in1
      - switch.turn_off: motor_in2
      - delay: !lambda "return id(close_delay).state * 1000;"
      - script.execute: stop_door

  - id: stop_door
    then:
      - switch.turn_off: motor_in1
      - switch.turn_off: motor_in2

binary_sensor:
  - platform: template
    name: "${friendly_name} - Vacuum Door Status Internal"
    id: door_open
    lambda: |-
      return id(door_state_open);
  - platform: gpio
    pin:
      number: ${switch_pin}
      mode: INPUT_PULLUP
    name: "${friendly_name} - Vacuum Door Micro Switch Door Status"
    device_class: "power"
    id: door_state_open_switch
    filters:
      - invert: true

# Define actions to control the door
button:
  - platform: template
    name: "Open Vacuum Door"
    on_press:
      - if:
          condition:
            lambda: return ${enable_microswitch} === true;
          then:
            - if:
                condition:
                  binary_sensor.is_off: door_state_open_switch
                then:
                  - script.execute: open_door
                else:
                  - logger.log: "Door is already open"
          else:
            - if:
                condition:
                  lambda: return !id(door_state_open);
                then:
                  - script.execute: open_door
                else:
                  - logger.log: "Door is already open"
    icon: "mdi:door-open"

  - platform: template
    name: "Close Vacuum Door"
    on_press:
      - if:
          condition:
            lambda: return ${enable_microswitch} === true;
          then:
            - if:
                condition:
                  binary_sensor.is_on: door_state_open_switch
                then:
                  - script.execute: close_door
                else:
                  - logger.log: "Door is already closed"
          else:
            - if:
                condition:
                  lambda: return id(door_state_open);
                then:
                  - script.execute: close_door
                else:
                  - logger.log: "Door is already closed"
    icon: "mdi:door-closed"

  - platform: template
    name: "Stop Vacuum Door"
    on_press:
      - script.execute: stop_door
      - globals.set:
          id: door_state_open
          value: "true"
    icon: "mdi:stop"

  - platform: template
    name: "Toggle Vacuum Status"
    on_press:
      - if:
          condition:
            lambda: return id(door_state_open);
          then:
            - globals.set:
                id: door_state_open
                value: "false"
          else:
            - globals.set:
                id: door_state_open
                value: "true"
